### ISSUE TITLE
What's the point of the airfrans librairy ?

### ISSUE THREAD

**Issue by Bulbille** [IRT-SystemX/ml4physim_startingkit#4]
Hello, 
In notebook 2, we use airefrans
In notebook 3 and so on, we use lips.

All the trainings and benchmarks are done with lips library. 

-  Why would you bother explaining how to use airfrans, when it's not used anywhere ?
- [ ] Missing requirements.txt for lips install, used in notebook 4. 
- "pip install Lips" seems to need Microsoft Visual C++ >14.0. The IT service within my company blocks the installation of that package. 
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by Mleyliabadi** [comment]
Hello,

The [LIPS framework](https://github.com/IRT-SystemX/LIPS) is the main tool to import the dataset and to evaluate the outputs. It provides also a set of utilities facilitating the design and training of augmented simulators (neural networks). It will also be used for the final evaluation of models when they are submitted on Codabench and to attribute a score.

As the studied usecase concerns the Airfoil, we thought that providing some details concerning the Airfoil simulator (AirfRANS library) may be useful for the participants to better understand the use case. Otherwise, we are agree with you that you don't need this package for the challenge. 

Concerning your second point, we don't have yet a Pypi repository for LIPS package, and I'm afraid that what you are trying to install might not be the appropriate repository. Try to follow the [LIPS framework installation procedure](https://github.com/IRT-SystemX/LIPS#installation) by cloning the [Github repository](https://github.com/IRT-SystemX/LIPS).

Don't hesitate to contact if you meet further problems or have other questions.

**Comment by Mleyliabadi** [comment]
Furthermore, the AirfRANS library is used to download the required data for the competition.

**Comment by daviddanan** [comment]
Nothing to add to Milad comments. 
For the airfoil usecase, and for user convenience, airfrans library required features are "wrapped" by LIPS, here are the module Milad refers to in this case:

- [AirfRANS dataset](https://github.com/IRT-SystemX/LIPS/blob/main/lips/dataset/airfransDataSet.py )
- [AirfRANS evaluation](https://github.com/IRT-SystemX/LIPS/blob/main/lips/evaluation/airfrans_evaluation.py)

Closing the issue, if you have others questions on theses aspects, don't hesitate to reopen it.
